# pin this to master to pull in the macOS changes
# can likely remove for 1.43
[[override]]
  branch = "master"
  name = "github.com/sevlyar/go-daemon"

# pin this to master to pull in the fix for linux/mips
# can likely remove for 1.43
[[override]]
  branch = "master"
  name = "github.com/coreos/bbolt"

[[constraint]]
  branch = "master"
  name = "github.com/Azure/azure-storage-blob-go"
